name: CI
on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Remove deprecated git config
      run: |
        git config --global --unset http.https://github.com/.extraheader
        
    - uses: actions/checkout@v3
      with:
        node-version: 20
        
    - name: Get Date
      id: get-date
      run: |
        echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        
    - uses: actions/cache@v3
      with:
        node-version: 20
        
    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: .buildozer_global
        key: buildozer-global-${{ hashFiles('buildozer.spec') }}
        
    - uses: actions/cache@v3
      with:
        path: .buildozer
        key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}
        
    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        command: buildozer android debug
        buildozer_version: stable
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: ${{ steps.buildozer.outputs.filename }}
